sound.new("Roof","/Assets/Roof_Floor.mp3","stream")
sound.new("Ground","/Assets/Ground_Floor.mp3","stream")
sound.new("Main","/Assets/Main_Floor.mp3","stream")
sound.new("Scary_1","/Assets/Midnight_Horror.mp3","stream")
sound.new("Scary_2","/Assets/Underworld_Bash.mp3","stream")

sound.new("EpT1","/Assets/episode_1_theme.mp3","stream")
sound.new("EpT1_L","/Assets/Ep1T_Lyrics.mp3","stream")
sound.new("EpT1_G","/Assets/Ep1T_Guitar.mp3","stream")
sound.new("EpT1_B","/Assets/Ep1T_Bass.mp3","stream")
sound.new("EpT1_D","/Assets/Ep1T_Drums.mp3","stream")

sound.new("EpT2","/Assets/episode_2_theme.mp3","stream")
sound.new("EpT2_L","/Assets/Ep2T_Lyrics.mp3","stream")
sound.new("EpT2_G","/Assets/Ep2T_Guitar.mp3","stream")
sound.new("EpT2_B","/Assets/Ep2T_Bass.mp3","stream")
sound.new("EpT2_D","/Assets/Ep2T_Drums.mp3","stream")

sound.new("EpT3","/Assets/episode_3_theme.mp3","stream")
sound.new("EpT3_L","/Assets/Ep3T_Lyrics.mp3","stream")
sound.new("EpT3_G","/Assets/Ep3T_Guitar.mp3","stream")
sound.new("EpT3_B","/Assets/Ep3T_Bass.mp3","stream")
sound.new("EpT3_D","/Assets/Ep3T_Drums.mp3","stream")

sound.new("EpT4","/Assets/episode_4_theme.mp3","stream")
sound.new("EpT4_L","/Assets/Ep4T_Lyrics.mp3","stream")
sound.new("EpT4_G","/Assets/Ep4T_Guitar.mp3","stream")
sound.new("EpT4_B","/Assets/Ep4T_Bass.mp3","stream")
sound.new("EpT4_D","/Assets/Ep4T_Drums.mp3","stream")

sound.new("EpT5","/Assets/episode_5_theme.mp3","stream")
sound.new("EpT5_L","/Assets/Ep5T_Lyrics.mp3","stream")
sound.new("EpT5_G","/Assets/Ep5T_Guitar.mp3","stream")
sound.new("EpT5_B","/Assets/Ep5T_Bass.mp3","stream")
sound.new("EpT5_D","/Assets/Ep5T_Drums.mp3","stream")

sound.new("EpT6","/Assets/episode_6_theme.mp3","stream")
sound.new("EpT6_L","/Assets/Ep6T_Lyrics.mp3","stream")
sound.new("EpT6_G","/Assets/Ep6T_Guitar.mp3","stream")
sound.new("EpT6_B","/Assets/Ep6T_Bass.mp3","stream")
sound.new("EpT6_D","/Assets/Ep6T_Drums.mp3","stream")

sound.new("EpT7","/Assets/episode_7_theme.mp3","stream")
sound.new("EpT7_L","/Assets/Ep7T_Lyrics.mp3","stream")
sound.new("EpT7_G","/Assets/Ep7T_Guitar.mp3","stream")
sound.new("EpT7_B","/Assets/Ep7T_Bass.mp3","stream")
sound.new("EpT7_D","/Assets/Ep7T_Drums.mp3","stream")

sound.new("Talk_1","/Assets/talk_1_normal.mp3","static")
sound.new("Talk_2","/Assets/talk_1_slow.mp3","static")
sound.new("Talk_3","/Assets/talk_1_fast.mp3","static")

sound.new("noodle_1","/Assets/noodle_1.mp3","static")
sound.new("noodle_2","/Assets/noodle_2.mp3","static")
sound.new("noodle_3","/Assets/noodle_3.mp3","static")
sound.new("noodle_4","/Assets/noodle_4.mp3","static")
sound.new("noodle_5","/Assets/noodle_5.mp3","static")
sound.new("noodle_6","/Assets/noodle_6.mp3","static")
sound.new("noodle_7","/Assets/noodle_7.mp3","static")

bs = sound.getSound("Main")
soundTick = ticker.new()
muted = false
